# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.11
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: mixed-line-ending

    - repo: https://github.com/mwouts/jupytext
      rev: v1.15.2
      hooks:
          - id: jupytext
            args: [--sync, --pipe, black]
            additional_dependencies:
                - black
                - isort

    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ['--profile', 'black']

    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black

    - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
      rev: v1.3.2
      hooks:
          - id: python-safety-dependencies-check
            files: requirements.txt
